### ISSUE TITLE
[question] how should I go about supporting migrating more than one database

### ISSUE THREAD

**Issue by jingyin** [dropwizard/dropwizard-flyway#21]
what's a good way to support migrating a number of `DataSourceFactory` in one DW service? I can probably add multiple `FlywayBundle` when overriding `Application#initialize`, but I don't know if this plugin supports picking the right `DataSourceFactory` to migrate via CLI args.

a workaround I can employ is to have one config file per database (having a different url) and pass that along when starting the app for migration, but the application would have to know how to pick the right set of migration files to apply under `db/migrate` which I'm not sure how to achieve.

**Comment by Maximusya** [comment]
- one flyway config file per database (`dbN_flyway.yml`) - with flyway's `locations` pointing to `db/migrate/dbN`;
- add a single `FlywayBundle` when overriding `Application#initialize` - if a shared `FlywayMigrationConfiguration` model can map all the dbN_flyway.yml;
- run each migration as `java -jar <jarfile> db migrate config/dbN_flyway.yml`

```
config
   app.yml
   db1_flyway.yml
   db2_flyway.yml
```
```
db
   migration
      db1
         V1_init.sql
      db2
         V1_init.sql
```
```yaml
dataSourceFactory:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/db1
flywayFactory:
  locations:
    - db/migration/db1
```
```yaml
dataSourceFactory:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/db2
flywayFactory:
  locations:
    - db/migration/db2
```
```java
package com.example.app.configuration;

import io.dropwizard.Configuration;
import io.dropwizard.db.DataSourceFactory;
import io.dropwizard.flyway.FlywayFactory;

public class FlywayMigrationConfiguration extends Configuration {

    private DataSourceFactory dataSourceFactory;
    private FlywayFactory flywayFactory;

    public DataSourceFactory getDataSourceFactory() {
        return dataSourceFactory;
    }

    public FlywayFactory getFlywayFactory() {
        return flywayFactory;
    }
}
```

```java
bootstrap.addBundle(new FlywayBundle<FlywayMigrationConfiguration>() {
    @Override
    public DataSourceFactory getDataSourceFactory(FlywayMigrationConfiguration configuration) {
        return configuration.getDataSourceFactory();
    }

    @Override
    public FlywayFactory getFlywayFactory(FlywayMigrationConfiguration configuration) {
        return configuration.getFlywayFactory();
    }
});
```

> java -jar app.jar db1 migrate config/db1_flyway.yml
> java -jar app.jar db2 migrate config/db2_flyway.yml
